### ISSUE TITLE
uploading file to nowhere

### ISSUE THREAD

**Issue by nambell** [cheems/Mega-to-Google-Drive#10]
Maybe I can't understand correctly how that script works, but after mount drive it said that "Mounted at /content/drive", ok, than I check next block and write that mega OUTPUT_PATH for downloading file\folder is / and link is basic link. Downloading complete and it said that "Download finished: / %Folder_from_the_link_name% ". But I opening my google drive account and there is no any /content/drive folder and also any downloaded files too... What I am doing wrong or softaware don't work correctly?

**Comment by cheems** [comment]
There may be some issues but sometimes things like this happen due to the runtime connection issues.

When you mount your drive, the root of your drive is the location which will be mounted at /content/drive. Let's say you have a folder named "mypics" in the root of your drive, now it will be appeared under the mount point as /content/drive/mypics.

If you give the output path as /content/drive/mypics , then transferred files can be found in the mypics folder in your drive. But the time it takes to appear the transferred files in that folder depends on the file size. The code in the transferring cell does is downloading the file from Mega to the colab session storage. Then it will be moved to your drive. It may take some time depending on the file size/number of files.

Probably your problem will be solved if you use another mounting method. Rclone or Google drive file stream
