### ISSUE TITLE
if this uses rclone 

### ISSUE THREAD

**Issue by Abimanyu007** [cheems/Mega-to-Google-Drive#12]
If it uses rclone can u make it server side transfer like 
rclone copy "MEGA:Folder" "GDrive:Folder" -P --drive-server-side-across-configs

**Comment by cheems** [comment]
I got your suggestion. But there is problem with that. It requires a Mega account. And also, files your are trying to transfer should be in your Mega storage. With rclone it is not possible to do that with Mega links. But if you want to transfer files that are already in your mega storage, you can do it. But even it is, I think that we can't use `--drive-server-side-across-configs` since Mega and Gdrive are different cloud storage services.
