### ISSUE TITLE
Unable to use anymore on free google colab

### ISSUE THREAD

**Issue by Paologioia** [cheems/Mega-to-Google-Drive#13]
Hi, your script seems run well, but when I start the transfer I'm instantly disconnected from the free colab runtime.

**Comment by ahmadmusyadada** [comment]
Nah, me too, when transfer still progress, suddenly disconnected and mount to drive again

**Comment by cheems** [comment]
I received several messages saying this on Telegram also. But I got no time to take a look at this. I checked it out today and it worked fine for me. But the problem you two have mentioned may occur due to several reasons.

<img src="https://i.imgur.com/YGaLirc.jpg" width="50%" alt="Open in a new tab to view in full size">

The most common reason would be Google has blacklisted this notebook because it uses a huge amount of bandwidth when considering the usage of all users (and its abusive behavior may cause also). In case of that, making a copy of this notebook and using it may solve the issue because making a copy will assign a new id to the new notebook. (But I'm not sure if it would solve the problem)

Also, your runtime can be disconnected due to the high demand for resources when you try to use it. This happens because Colab is always trying to prioritize premium users so resources assigned to free users will be reassigned to prioritized users on demand.

I don't know which factors they consider when assigning resources to free users when there is high demand. But I think your previous usage will also be considered. Suppose previously you have used Colab more often for running notebooks like this one(notebooks that have kind of abusive behavior). Most of the time your resources will be reassigned to fresh users or users who hardly use them. Also, these factors may vary from one country to another due to the usage and the amount of resources allocated for a specific region. 

There may be many reasons, but these are the only ones that I can think of at the moment.

**Comment by chinthub** [comment]
There seems to be an issue for me with larger file sizes. Can you once try with >3GB size and check if it disconnects or not? 
Note : I did try copying the script to my drive but it still disconnects. It would be of utmost help if you could find a way out of it

**Comment by cheems** [comment]
Now I think that colab disconnects from sessions because MegaCMD the tool used in the script, which is Mega's official CLI client, uses resources abusively. That's why I stopped trying update the script. Anyways I will do something regarding that after finding a workaround.

**Comment by CuddlyPaws** [comment]
> Now I think that colab disconnects from sessions because MegaCMD the tool used in the script, which is Mega's official CLI client, uses resources abusively. That's why I stopped trying update the script. Anyways I will do something regarding that after finding a workaround.

hi did you find anything
